name: Deploy Documentation (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'docs-site/**'
      - '.github/workflows/deploy-docs-dev.yml'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-dev"
  cancel-in-progress: false

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs-site/package-lock.json

      - name: Install dependencies
        run: cd docs-site && npm ci

      - name: Build documentation
        run: cd docs-site && npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: docs-site/build
          
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📖 Documentation preview built successfully! Check the build artifact for preview.'
            })